#!/usr/bin/env python3
"""Generate the little glow masks of Brimstone Caldera.

A glow mask is the luminous accent of one sprite: fully transparent everywhere except
the pixels that should read as self-lit (firebloom's throat, crystal glints, ember-kelp
heat veins, the sulfur droplet's specular). The masks are DERIVED from the base sprites
generated by the other scripts, so they can never drift out of pixel alignment: each
rule classifies the base palette and boosts only the hot subset. Models render these on
an inflated overlay box with full-bright neoforge face data.
"""

from __future__ import annotations

import struct
import zlib
from pathlib import Path
from typing import Callable, List, Tuple

BLOCK = Path("src/main/resources/assets/aquanaut/textures/block")
RGBA = Tuple[int, int, int, int]
Grid = List[List[RGBA]]


def read_png(path: Path) -> Grid:
    data = path.read_bytes()
    width, height = struct.unpack(">II", data[16:24])
    idat = bytearray()
    offset = 8
    while offset < len(data):
        length = struct.unpack(">I", data[offset:offset + 4])[0]
        tag = data[offset + 4:offset + 8]
        if tag == b"IDAT":
            idat.extend(data[offset + 8:offset + 8 + length])
        offset += 12 + length
    raw = zlib.decompress(bytes(idat))
    stride = width * 4
    grid: Grid = []
    previous = bytearray(stride)
    position = 0
    for _ in range(height):
        filter_type = raw[position]
        row = bytearray(raw[position + 1:position + 1 + stride])
        position += 1 + stride
        if filter_type == 0:
            pass
        elif filter_type == 1:  # Sub
            for i in range(4, stride):
                row[i] = (row[i] + row[i - 4]) & 0xFF
        elif filter_type == 2:  # Up
            for i in range(stride):
                row[i] = (row[i] + previous[i]) & 0xFF
        else:
            raise AssertionError(f"unsupported PNG filter {filter_type} in {path}")
        previous = row
        grid.append([(row[i], row[i + 1], row[i + 2], row[i + 3]) for i in range(0, stride, 4)])
    return grid


def write_png(path: Path, grid: Grid) -> None:
    height = len(grid)
    width = len(grid[0])
    raw = bytearray()
    for row in grid:
        raw.append(0)
        for r, g, b, a in row:
            raw.extend((max(0, min(255, int(r))), max(0, min(255, int(g))),
                        max(0, min(255, int(b))), max(0, min(255, int(a)))))

    def chunk(tag: bytes, payload: bytes) -> bytes:
        return (struct.pack(">I", len(payload)) + tag + payload
                + struct.pack(">I", zlib.crc32(tag + payload) & 0xFFFFFFFF))

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    path.write_bytes(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
                     + chunk(b"IDAT", zlib.compress(bytes(raw), 9)) + chunk(b"IEND", b""))
    print(f"wrote {path}")


def luma(px: RGBA) -> float:
    return 0.299 * px[0] + 0.587 * px[1] + 0.114 * px[2]


def glow_mask(base: Grid, rule: Callable[[RGBA], RGBA | None], name: str) -> Grid:
    out: Grid = [[(0, 0, 0, 0) for _ in row] for row in base]
    lit = 0
    for y, row in enumerate(base):
        for x, px in enumerate(row):
            if px[3] < 32:
                continue
            glow = rule(px)
            if glow is not None:
                out[y][x] = (*glow, 255)
                lit += 1
    total = len(base) * len(base[0])
    assert lit < total * 0.45, f"{name}: glow mask too broad ({lit}/{total}) - keep it an accent"
    print(f"  {name}: {lit} lit pixels")
    return out


# --- classification rules ---------------------------------------------------

def firebloom_rule(px: RGBA) -> RGBA | None:
    r, g, b, _ = px
    # The emissive throat and petal glints: everything warm and hot.
    if r > 150 and b < r - 40:
        return (min(255, int(r * 1.12)), min(255, int(g * 1.05)), min(255, int(b * 0.9 + 20)))
    return None


def crystal_rule(px: RGBA) -> RGBA | None:
    # Only the sharpest facet glints carry the sparkle.
    return (255, 244, 198) if luma(px) > 192 else None


def fumarole_rule(px: RGBA) -> RGBA | None:
    r, g, b, _ = px
    if r > 140 and g > 115 and b < 105:
        return (min(255, int(r * 1.1)), min(255, int(g * 1.02)), 90)
    return None


def kelp_rule(px: RGBA) -> RGBA | None:
    r, g, b, _ = px
    heat = luma(px)
    # Only the dark heat veins and the bright rim light - the blade body stays dead.
    if r > 130 and r > b + 55 and (heat < 95 or heat > 138):
        return (min(255, int(r * 1.15)), min(255, int(g * 1.05 + 10)), min(255, b + 30))
    return None


def droplet_rule(px: RGBA) -> RGBA | None:
    # The one bright specular on the sulfur teardrop.
    return (255, 250, 224) if luma(px) > 205 else None


def calcite_rule(px: RGBA) -> RGBA | None:
    # Brine Mirror Gorge: the quill tips carry the same cold glint language.
    return (255, 252, 240) if luma(px) > 205 else None


JOBS = [
    ("firebloom", firebloom_rule),
    ("sulfur_crystal", crystal_rule),
    ("fumarole", fumarole_rule),
    ("ember_kelp_top", kelp_rule),
    ("ember_kelp_body", kelp_rule),
    ("ember_kelp_tail", kelp_rule),
    ("sulfur_stalactite_tail", droplet_rule),
    ("calcite_quill", calcite_rule),
]


def main() -> None:
    print("brimstone caldera glow masks:")
    for name, rule in JOBS:
        base = read_png(BLOCK / f"{name}.png")
        write_png(BLOCK / f"{name}_glowmask.png", glow_mask(base, rule, name))


if __name__ == "__main__":
    main()
